name: Build and Release Artifacts

on:
  workflow_dispatch:
    inputs:
      build_linux:
        description: 'Build for Linux'
        required: false
        default: true
        type: boolean
      build_macos:
        description: 'Build for macOS'
        required: false
        default: true
        type: boolean
      build_windows:
        description: 'Build for Windows'
        required: false
        default: true
        type: boolean

jobs:
  build-linux:
    if: ${{ github.event.inputs.build_linux == 'true' }}
    name: Build (Linux)
    runs-on: codebuild-wso2_product-integrator-${{ github.run_id }}-${{ github.run_attempt }}
    defaults:
      run:
        working-directory: lib/vscode
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: lib/vscode/.nvmrc
          cache: npm
          cache-dependency-path: lib/vscode/package-lock.json

      - name: Install system dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config xvfb libgtk-3-0 libxkbfile-dev libkrb5-dev libgbm1 rpm zip

      - name: Prepare artifacts dir
        run: |
          mkdir -p ../artifacts

      - name: Install dependencies
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
        run: |
          npm ci

      - name: Get latest lib/vscode rev
        id: vscode-rev
        run: echo "rev=$(git rev-parse HEAD:./lib/vscode)" >> $GITHUB_OUTPUT
  
      - name: Fetch prebuilt Code package from cache
        id: cache-vscode
        uses: actions/cache@v4
        with:
          path: lib/vscode-reh-web-*
          key: vscode-reh-package-v1-${{ steps.vscode-rev.outputs.rev }}-${{ hashFiles('patches/*.diff', 'ci/build/update-product.sh') }}

      - name: Fetch extensions from cache
        uses: actions/cache@v4
        with:
          path: lib/vscode/.build/extensions
          key: vscode-reh-extensions-v1-${{ steps.vscode-rev.outputs.rev }}-${{ hashFiles('patches/*.diff', 'ci/build/update-product.sh') }}

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: quilt
          version: 1.0

      - name: Apply patches
        run: quilt push -a
  
      - name: Update product.json and branding
        working-directory: .
        run: |
          chmod +x ./ci/build/update-product.sh
          ./ci/build/update-product.sh

      - name: Mixin distro modules
        run: |
          node build/azure-pipelines/distro/mixin-npm || true
          node build/azure-pipelines/distro/mixin-quality || true

      - name: Build client (Linux)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run gulp vscode-linux-x64-min-ci
          ARCHIVE_PATH=../artifacts/vscode-linux-x64.tar.gz
          tar -czf "$ARCHIVE_PATH" -C .. VSCode-linux-x64

      - name: Build Linux packages (deb, rpm)
        run: |
          npm run gulp "vscode-linux-x64-prepare-deb"
          npm run gulp "vscode-linux-x64-build-deb"
          npm run gulp "vscode-linux-x64-prepare-rpm"
          npm run gulp "vscode-linux-x64-build-rpm"
          # Copy outputs
          cp .build/linux/deb/*/deb/*.deb ../artifacts/ || true
          cp .build/linux/rpm/*/*.rpm ../artifacts/ || true

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux
          path: |
            lib/vscode/../artifacts/*
          if-no-files-found: error

  build-macos:
    if: ${{ github.event.inputs.build_macos == 'true' }}
    name: Build (macOS)
    runs-on: macos-latest
    defaults:
      run:
        working-directory: lib/vscode
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: lib/vscode/.nvmrc
          cache: npm
          cache-dependency-path: lib/vscode/package-lock.json

      - name: Validate Xcode tools (macOS)
        run: |
          xcode-select -p
          python3 -m pip install --user setuptools || true

      - name: Prepare artifacts dir
        run: |
          mkdir -p ../artifacts

      - name: Install dependencies
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
        run: |
          npm ci

      - name: Mixin distro modules
        run: |
          node build/azure-pipelines/distro/mixin-npm || true
          node build/azure-pipelines/distro/mixin-quality || true

      - name: Build client (macOS)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run gulp vscode-darwin-x64-min-ci
          ARCHIVE_PATH=../artifacts/VSCode-darwin-x64.zip
          (cd .. && zip -qry "$ARCHIVE_PATH" VSCode-darwin-x64)

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-darwin
          path: |
            lib/vscode/../artifacts/*
          if-no-files-found: error

  build-windows:
    if: ${{ github.event.inputs.build_windows == 'true' }}
    name: Build (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: lib/vscode
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: lib/vscode/.nvmrc
          cache: npm
          cache-dependency-path: lib/vscode/package-lock.json

      - name: Prepare artifacts dir
        run: |
          mkdir -p ../artifacts

      - name: Install dependencies
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
        run: |
          npm ci

      - name: Mixin distro modules
        run: |
          node build/azure-pipelines/distro/mixin-npm || true
          node build/azure-pipelines/distro/mixin-quality || true

      - name: Build client (Windows)
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run gulp "vscode-win32-x64-min-ci"
          $archivePath = "../artifacts/VSCode-win32-x64.zip"
          Compress-Archive -Path ../VSCode-win32-x64/* -DestinationPath $archivePath -Force

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-win32
          path: |
            lib/vscode/../artifacts/*
          if-no-files-found: error
